### ISSUE TITLE
rsync failed to set permissions

### ISSUE THREAD

**Issue by rgommers** [scipy/docs.scipy.org#31]
After trying to sync gh-30 just now, I get:
```
$ make upload USER=rgommers
rsync -r -p build/dist/ rgommers@docs.scipy.org:/srv/docs_scipy_org/doc/
rsync: failed to set permissions on "/srv/docs_scipy_org/doc/.": Operation not permitted (1)
rsync: failed to set permissions on "/srv/docs_scipy_org/doc/_sources": Operation not permitted (1)
rsync: failed to set permissions on "/srv/docs_scipy_org/doc/_static": Operation not permitted (1)
rsync: failed to set permissions on "/srv/docs_scipy_org/doc/_static/css": Operation not permitted (1)
rsync: failed to set permissions on "/srv/docs_scipy_org/doc/_static/img": Operation not permitted (1)
rsync: failed to set permissions on "/srv/docs_scipy_org/doc/_static/js": Operation not permitted (1)
rsync: failed to set permissions on "/srv/docs_scipy_org/doc/_static/less": Operation not permitted (1)
rsync: failed to set permissions on "/srv/docs_scipy_org/doc/_static/less/bootstrap": Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1209) [sender=3.1.3]
make: *** [upload] Error 23
```

The doc upload did work, and the `1.3.2` docs appear to be fine. Perhaps after an update the `www-data` group permissions can not be changed anymore. By default `rsync -r -p` only works for files if the user doing the rsync is already the owner or is root. IIRC there was some workaround for that, but I don't remember which one or why it was needed. Maybe the `-p` should simply be removed.

**Comment by tylerjereddy** [comment]
I think the username/file owner on the machine I used was different than the one I used with `make upload ...` if that is what you mean?

I think `tyler` owns the files on the machine & `treddy` is the upload `USER` on the command line. I use a different machine for `make dist` because it is more reliable on an another Ubuntu machine for me.

**Comment by rgommers** [comment]
No that's not what I mean, your upload seemed fine. You uploaded the built docs, I'm talking about the `rsync` of the last commit to this repo, which I did today and which showed the reported permission errors.

**Comment by lucascolley** [comment]
can this be closed?

**Comment by rgommers** [comment]
Yeah I think so. @tylerjereddy has done most of the recent uploads though, so I'll leave it to him to close.

**Comment by tylerjereddy** [comment]
haven't seen the problem recently
