### ISSUE TITLE
Sphinx URL is wrong

### ISSUE THREAD

**Issue by ogauthe** [scipy/docs.scipy.org#36]
Hello,

This is really a detail. There is an URL for sphinx at the end of every documentation page that links to http://sphinx.pocoo.org/. This page is dead and according to http://www.pocoo.org/, it will probably stay that way. The link should send to http://www.sphinx-doc.org/.

**Comment by rgommers** [comment]
Thanks for the report @gauthe.

The way to fix this is to update the Sphinx theme: https://github.com/scipy/scipy-sphinx-theme/blob/master/_theme/scipy/layout.html#L261,
then update the submodule in this repo and in the other repos using that theme, and finally redeploying. 

So unfortunately not completely trivial. Pragmatic course of action would be to fix the link in the theme and leave it at that; the rest will then fix itself over time. I'll do that now I think.

**Comment by rgommers** [comment]
And double-checked that the new Sphinx theme doesn't contain this issue.
