### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/docs.scipy.org#49]
Trying to upload the latest docs build: `make upload USERNAME=treddy RELEASE=1.6.2` I get `cp: /srv/docs_scipy_org/doc/scipy-1.6.2/dist.tar.gz: No space left on device`

![image](https://user-images.githubusercontent.com/7903078/112565940-b0c7c580-8da3-11eb-9980-9f7028e7cf8c.png)

@rgommers Not sure how comfortable I am poking around on that server filesystem--suggestions?

**Comment by rgommers** [comment]
It's full indeed:
```
$ df  -H
Filesystem      Size  Used Avail Use% Mounted on
udev            1.1G     0  1.1G   0% /dev
tmpfs           210M   22M  188M  11% /run
/dev/xvda1       13G   12G  525M  96% /
```
There isn't much we'd want to get rid of. It's an AWS server so it should not be hard to resize the drive - I'll ask the sysadmin.

**Comment by tylerjereddy** [comment]
I think it has been dealt with now because the upload just succeeded--thanks for sorting it out
