### ISSUE TITLE
Bad relatie links on https://docs.scipy.org/doc/scipy/reference/ 

### ISSUE THREAD

**Issue by ivanistheone** [scipy/docs.scipy.org#57]
Hello, I was recently browsing the scipy docs reference/ site: https://docs.scipy.org/doc/scipy/reference/index.html and noticed some link problems with the nav bar:
 - the link "Getting started" 404s: https://docs.scipy.org/doc/scipy/reference/getting_started.html
 - navigating to "API reference" renders weirdly https://docs.scipy.org/doc/scipy/reference/reference/index.html because the  _image and _static assets are not present

The same two links work fine work on the main docs page:  https://docs.scipy.org/doc/scipy/
 - the link "Getting started" points to https://docs.scipy.org/doc/scipygetting_started.html
 - the link "API reference" points to https://docs.scipy.org/doc/scipy/reference/index.html

so the seems to be the relative links in the header:
- when resolved relative to https://docs.scipy.org/doc/scipy/ the links are fine
- when resolved relative to https://docs.scipy.org/doc/scipy/reference/ the relative link don't work

One possible fix would be to use absolute paths in the nav header 
- `/doc/scipy/reference/getting_started.html`
- `/doc/scipy/reference/index.html` 

<img width="1015" alt="Screen Shot 2021-09-17 at 12 47 27 PM" src="https://user-images.githubusercontent.com/163966/133824796-1ef9a760-26fc-42c3-9c82-c12273e79551.png">

Unfortunately I wasn't able to find the source code for this element to make this change. If someone were to point me in the right direction, I'll be happy to submit a PR to fix this.

**Comment by rgommers** [comment]
Yes it's a mess, sorry about that. Not easy to fix, should be done for the 1.7.2 release - see https://github.com/scipy/scipy/issues/14267 for details.

I'll close this issue as a duplicate. Thanks for the report @ivanistheone

**Comment by slel** [comment]
Thanks for opening this issue. The "getting started" page is at

- https://docs.scipy.org/doc/scipy/getting_started.html

rather than

- https://docs.scipy.org/doc/scipy/reference/getting_started.html
