### ISSUE TITLE
Upload 1.7.2 docs

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/docs.scipy.org#59]
For now I'm delaying the build/upload of the SciPy `1.7.2` docs because:

1) The doc theme means that this will guarantee that we break intersphinx/other links, get an avalanche of issues/waste time triaging those, and then eventually patch some of them with manual work by one of two maintainers on the doc server
2) We're just releasing our first wheels for `3.10`, so would be good to focus on any issues related to that before breaking the docs upload again

**Comment by tupui** [comment]
What about if we merged this repo with `scipy.org`? Do we need to have this other space?

We should have the same theme and not deal anymore with NumPy.

**Comment by rgommers** [comment]
+1 for delaying doc upload. there are no interesting changes in the docs anyway

> What about if we merged this repo with scipy.org? Do we need to have this other space?

Yes we should do that.

**Comment by lucascolley** [comment]
(this site is no longer updated now that we have version switchers for NumPy and SciPy)
