### ISSUE TITLE
Broken link to reference guide

### ISSUE THREAD

**Issue by inducer** [scipy/docs.scipy.org#61]
If I go to

https://docs.scipy.org/doc/

and click on "SciPy Reference Guide", I get sent here:

https://docs.scipy.org/doc/scipy/reference/

which gives me a 404 Not Found error.

**Comment by astrojuanlu** [comment]
Redirects are now in place, I think.

**Comment by tylerjereddy** [comment]
I've been trying to manually patch the redirects here: https://github.com/tylerjereddy/htaccess_backup/pull/1

Concrete suggestions for improvement are welcome

**Comment by rgommers** [comment]
This one works, closing. Thanks all
