### ISSUE TITLE
docs.scipy.org refusing connections

### ISSUE THREAD

**Issue by danking** [scipy/docs.scipy.org#69]
To whom it may concern, it appears the scipy docs server is not accepting connections? We're trying to rebuild our docs and we need the objects.inv file.

Is this the right place to report this?

```
# curl -vvv https://www.docs.scipy.org
*   Trying 50.17.248.72:443...
* connect to 50.17.248.72 port 443 failed: Connection refused
* Failed to connect to www.docs.scipy.org port 443 after 20 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to www.docs.scipy.org port 443 after 20 ms: Connection refused
# date
Mon Oct 31 19:00:58 EDT 2022
```

**Comment by tupui** [comment]
Hi @danking, thanks for reporting. Actually the doc is down https://docs.scipy.org/doc/scipy/ cc @rgommers @tylerjereddy 

Otherwise the correct config for Sphinx is
```
intersphinx_mapping = {
    ...,
    'scipy': ('https://docs.scipy.org/doc/scipy/', None),
}
```

**Comment by tylerjereddy** [comment]
hmm, I tried `make upload ..` for `docs.scipy.org` but it didn't help; I can definitely `ssh` into the server though

**Comment by tylerjereddy** [comment]
I tried messing around with the symbolic links in case there was some `1.9.3` specific issues, but didn't seem to help. I'll stop for now before I make a bigger mess.

**Comment by rgommers** [comment]
Hmm, no idea what is going on here. I can ssh in as well, things seem fine in `/srv/docs_scipy_org/`. I don't have permissions to look at server logs (nor am I any good at that). 

The one thing that changed yesterday is that I merged https://github.com/scipy/docs.scipy.org/pull/68 and ran:
```
make dist
touch output-is-fine
make upload USER=rgommers
```
in a clone of this repo. That worked fine though; at least I refreshed my browser after and ensured that the links to the new `1.9.3` docs were visible and working. The `.htaccess` files seem fine as well. For completeness, here are their contents:

```bash
rgommers@www:/srv/docs_scipy_org$ cat .htaccess 
RewriteEngine on
RewriteRule ^/?$ /doc/ [R,L]

$ cat doc/.htaccess 
Options +SymLinksIfOwnerMatch
RewriteEngine On

RewriteRule ^numpy(/.*) https://numpy.org/doc/stable$1 [R=permanent,L]

Redirect 301 /doc/scipy/reference/objects.inv /doc/scipy/objects.inv
```

EDIT: checked disk space as well, all fine:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            991M     0  991M   0% /dev
tmpfs           200M   21M  180M  11% /run
/dev/xvda1       12G  5.6G  5.6G  50% /
tmpfs          1000M     0 1000M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs          1000M     0 1000M   0% /sys/fs/cgroup
tmpfs          1000M     0 1000M   0% /run/shm
/dev/xvdg1      296G  8.9G  272G   4% /srv
tmpfs           200M     0  200M   0% /run/user/1004
```

I'll go ask for some sysadmin help.

**Comment by rgommers** [comment]
It's fixed.

**Comment by rgommers** [comment]
For the record, there was an issue with the certificate for the domain.

**Comment by tupui** [comment]
Great thanks Ralf 👍

**Comment by rgommers** [comment]
All the credits go to Enthought here, they're good at maintaining that server for us.

**Comment by danking** [comment]
Thank you all!
